
name: ondemand release Workflow

on:
  workflow_dispatch:
   inputs:
      ReleaseNo:
        description: 'Enter Release name'
        required: true
        default: '2.5.3'

env:
  WORKFLOW_VARIABLE: WORKFLOW

jobs:
  build:
    runs-on: [ubuntu-org,ubuntu-org4]
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: "checkout"
        uses: actions/checkout@v2
#      - name: Set up Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v2
#        with:
#          node-version: ${{ matrix.node-version }} 
#      - name: Install dependencies
#        run: npm install
#      - name: sample curl call
#        run: |
#          curl https://meowfacts.herokuapp.com/ | jq '.data[0]'
#        id: samplecurl
#      - name: Set the value
#        id: step_one
#        run: |
#          echo "test=$(curl https://meowfacts.herokuapp.com/ | jq '.data[0]' )" >> $GITHUB_ENV
#      - name: Use the value
#        id: step_two
#        run: |
#          echo "$test" # This will output 'yellow'
      - name: "Perform SOD Check"
        run: |
          echo "Perform SOD Check" 
      - name: "create service now ticket"
        run: |
          echo "create service now ticket" 
      - name: "create sharepoint folder"
        run: |
          echo "sharepoint folder creation" 
      - name: "create an workitem for Compliance team"
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ SECRETS.GIT_PER_TOKEN }}
          owner: imurpalvicky-org
          repo: compliance-team
          title: New Replease -<GEAR_ID>-${{ github.event.inputs.ReleaseNo }}
          body: |
            # Body
            New Release created verify the artifacts and close the issue with the comment "APPROVED"
          assignees: imurpalvicky
          labels: CHG456 ,gearid-1234
      - name: "create an workitem for App Release engineer team to kick start the release"
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ SECRETS.GIT_PER_TOKEN }}
          title: New Replease-<GEAR_ID>- ${{ github.event.inputs.ReleaseNo }}
          body:  |
            # Body
            Please close the issue  once the ADM approval is given, with the comment "GET STARTED" 
          assignees: imurpalvicky
          labels: CHG456 ,gearid-1234
